### ISSUE TITLE
Problems installing on Windows

### ISSUE THREAD

**Issue by mtravis** [robward-scisys/sldeditor#17]
I'm trying to install on windows 7 using the build instructions. I have the jdk and maven parts sorted but when I run `mvn clean install` it seems to tick along ok and then sticks here:

```
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.sldeditor.test.unit.extension.filesystem.ExtensionFactoryTest
Running com.sldeditor.test.unit.extension.filesystem.file.FileSystemInputTest
```

**Comment by robward-scisys** [comment]
I know what the issue is but I haven't got an elegant solution at the moment.

The issue is to do with trying to pre-populate the file system tree.
If the drive letters have a lot of folders/files then it can take a long time to populate the tree.

The tree should only be populated for the next folder level down.  When the a folder is opened, if it hasn't been populated before, the application goes away and populates the child folders and files.  If it has been populated before then is just displays what its got.

Currently what happens when the application starts up and in the unit test is that all the Windows drive letters are iterated through and the next level of folders and files are retrieved.  So that when the user opens up the drive letter in the tree the folders are displayed immediately.

Fortunately I can change a flag value to stop the pre-population of the first level of folders/files which should speed things up.  The downside is that when you expand a drive letter which contains a lot of folders/files there is no visual clue on the GUI to show its doing something.

I'll make the change to stop the pre-population of top level folders.  If the problem is to do with folder/file permissions you'll have to let me know.

**Comment by robward-scisys** [comment]
I've made the change, let me know if this has fixed the issue.

**Comment by mtravis** [comment]
The installation worked. I will have a go at editing SLDs and let you know how I get on.
