### ISSUE TITLE
occasional rendering problem

### ISSUE THREAD

**Issue by rghosh0** [robward-scisys/sldeditor#275]
Sometimes I see a rendering problem.  Seems to happen with the Belfast metro extracts roads a lot. At 00:40 in the following video you see it:

https://drive.google.com/file/d/0B9Kv4E5NP1kFTzk0UG1COW5sdnM/view?usp=sharing

**Comment by robward-scisys** [comment]
I think this has been fixed in the latest build.
I've added the ability to configure ranges for render transformations.  If the render transformation wasn't configured correctly it caused the renderer to exception and I've worked out how to catch it and recreate the renderer.  As part of the rendering I was adding the layer too many times which is the issue I think you are seeing.

**Comment by rghosh0** [comment]
Looks good!
